FROM python:3.13.7-slim

# Install TA-Lib system dependencies
RUN apt-get update && apt-get install -y build-essential wget \
	&& wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
	&& tar -xzf ta-lib-0.4.0-src.tar.gz \
	&& cd ta-lib && ./configure --prefix=/usr && make && make install \
	&& cd .. && rm -rf ta-lib ta-lib-0.4.0-src.tar.gz

RUN pip install -U pip

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py ./

COPY scripts ./scripts

COPY streamlit_app.py ./

COPY entrypoint.sh ./

RUN chmod +x entrypoint.sh

EXPOSE 8501

ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]